FROM python:3.14-slim
WORKDIR /app
COPY webapp.py .
COPY templates/ templates/
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
ENV PYTHONUNBUFFERED=1
CMD ["python", "webapp.py"]
