services:
  app:
    image: flairtimermodbot-app:dev
    container_name: mch-flairtimermodbot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./docker-config:/app/config
      - ./docker-DB:/app/DB
